name: qq_email_send

on: [push]

jobs:
  send_email:
    runs-on: ubuntu-latest
    env:
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
      RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print environment variables
      run: |
        echo "SENDER_EMAIL: $SENDER_EMAIL"
        echo "SENDER_PASSWORD: $SENDER_PASSWORD"
        echo "RECEIVER_EMAIL: $RECEIVER_EMAIL"
